version: '3.8'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    env_file: app/.env

  backend_api:

    build: app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/api
    command: bash -c '/bin/sh starter.sh'

    env_file: app/.env
    depends_on:
      - db

